import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';
import { generateMistralPrompt } from '@/lib/generateMistralPrompt';

export async function POST(req: Request) {
  try {
    const { memoryId } = await req.json();

    if (!memoryId) {
      return NextResponse.json({ error: 'Missing memoryId' }, { status: 400 });
    }

    // Init Supabase with Service Role Key for Admin Access
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // 1. Fetch Memory Data
    const { data: memory, error: fetchError } = await supabase
      .from('memories')
      .select('*')
      .eq('id', memoryId)
      .single();

    if (fetchError || !memory) {
      console.error('Error fetching memory:', fetchError);
      return NextResponse.json({ error: 'Memory not found' }, { status: 404 });
    }

    // Check payment status if needed (e.g. memory.payment_status === 'paid')
    // content_status could be 'draft', 'pending_generation', 'completed'

    // Fix: Handle null data safely
    const prompt = generateMistralPrompt(memory.data || {});

    // 3. Call Mistral AI
    const mistralResponse = await fetch('https://api.mistral.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.MISTRAL_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'mistral-large-latest',
        messages: [
          { role: 'system', content: 'Tu es un écrivain spécialisé dans les récits mémoriels.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 1500, // increased for safety
      }),
    });

    if (!mistralResponse.ok) {
      const errorText = await mistralResponse.text();
      console.error('Mistral API Error:', errorText);
      throw new Error(`Mistral API failed: ${mistralResponse.statusText}`);
    }

    const mistralData = await mistralResponse.json();
    const generatedText = mistralData.choices[0]?.message?.content || '';

    if (!generatedText) {
      throw new Error('No text generated by Mistral');
    }

    // 4. Update Memory in DB
    const { error: updateError } = await supabase
      .from('memories')
      .update({
        bio: generatedText,
        status: 'completed', // or 'generated'
        updated_at: new Date().toISOString(),
      })
      .eq('id', memoryId);

    if (updateError) {
      console.error('Error updating memory:', updateError);
      throw new Error('Failed to save generated text');
    }

    return NextResponse.json({ success: true, text: generatedText });

  } catch (error: any) {
    console.error('Generate Memorial Error:', error);
    return NextResponse.json(
      { error: error.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}
